/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aptech.project2.nhom2.gui.dialoguebox;

import java.util.List;
import java.util.stream.Collectors;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import aptech.project2.nhom2.dao.NguoiDungHeThongDAO;
import aptech.project2.nhom2.model.NguoiDungHeThong;
import aptech.project2.nhom2.util.Md5Gen;

/**
 *
 * @author Mirai
 */
public class DialogNguoiDung extends javax.swing.JDialog {

    /**
     * Creates new form DialogNguoiDung
     */

    private final String hashedDefault = Md5Gen.getMD5("12345678");

    private List<NguoiDungHeThong> userList;
    private List<NguoiDungHeThong> users;

    public DialogNguoiDung(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        loadData(null);

        this.setLocationRelativeTo(null);
    }

    private void loadData(String keyword) {
        userList = NguoiDungHeThongDAO.findAll();
        if (keyword == null) {
            users = userList.stream().filter(it -> it.getStatus() == 1 && it.getAdmin() != 1)
                    .collect(Collectors.toList());
        } else {
            users = userList.stream()
                    .filter(it -> it.getStatus() == 1 && it.getAdmin() != 1 && it.getUsername().equals(keyword))
                    .collect(Collectors.toList());
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        users.forEach(it -> {
            model.addRow(new Object[] { it.getFull_name(), it.getUsername(), });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnResetPw = new javax.swing.JButton();
        btnDeleteUsers = new javax.swing.JButton();
        btnResetInput = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý người dùng");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("THông tin người dùng"));

        jLabel2.setText("Họ tên");

        jLabel3.setText("Tên đăng nhập");

        jLabel4.setText("Mật khẩu");

        jLabel5.setText("Xác nhận lại mật khẩu");

        btnAddUser.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_add_16px.png"))); // NOI18N
        btnAddUser.setText("Thêm người dùng");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnResetPw.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_password_reset_16px.png"))); // NOI18N
        btnResetPw.setText("Đặt lại mật khẩu");
        btnResetPw.setEnabled(false);
        btnResetPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPwActionPerformed(evt);
            }
        });

        btnDeleteUsers.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_delete_16px.png"))); // NOI18N
        btnDeleteUsers.setText("Xóa người dùng");
        btnDeleteUsers.setEnabled(false);
        btnDeleteUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUsersActionPerformed(evt);
            }
        });

        btnResetInput.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_reset_16px.png"))); // NOI18N
        btnResetInput.setText("Điền lại");
        btnResetInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2).addGap(90, 90, 90)
                                        .addComponent(txtFullName))
                                .addGroup(
                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                        jPanel1Layout
                                                .createSequentialGroup().addComponent(jLabel5).addGap(
                                                        18, 18, 18)
                                                .addComponent(txtRePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 275,
                                                        Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                        .createSequentialGroup()
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3).addComponent(jLabel4))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtUsername).addComponent(txtPassword))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAddUser, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addComponent(btnResetInput, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addComponent(btnResetPw, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addComponent(btnDeleteUsers, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                        .addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnResetPw, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeleteUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10).addComponent(btnResetInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(13, 13, 13)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel4).addComponent(txtPassword,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel5).addComponent(txtRePassword,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jLabel1.setText("Tìm tên đăng nhập");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_search_16px.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] { "Họ tên", "Tên đăng nhập" }) {
            boolean[] canEdit = new boolean[] { false, false };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(txtTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnTimKiem)
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddUserActionPerformed
        if (txtFullName.getText().isEmpty() || txtFullName.getText().isEmpty() || txtPassword.getPassword().length == 0
                || txtRePassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy dủ các thông tin trước khi thêm người dùng",
                    "Thiếu dữ liệu", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        NguoiDungHeThong test = users.stream().filter(it -> it.getUsername().equals(txtUsername.getText())).findAny()
                .orElse(null);

        if (test != null) {
            JOptionPane.showMessageDialog(null, "Tên đăng nhập đã tồn tại trong hệ thống", "Tên đăng nhập đã tồn tại",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (!new String(txtPassword.getPassword()).equals(new String(txtRePassword.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Xác nhận mật khẩu không khớp. Vui lòng kiểm tra lại",
                    "Mật khẩu không khớp", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String hashedPW = Md5Gen.getMD5(new String(txtPassword.getPassword()));

        NguoiDungHeThongDAO.addNew(new NguoiDungHeThong(txtFullName.getText(), txtUsername.getText(), hashedPW));

        JOptionPane.showMessageDialog(null, "Đã thêm người dùng thành công", "Thêm người dùng",
                JOptionPane.INFORMATION_MESSAGE);
        loadData(null);
        btnResetInputActionPerformed(null);

    }// GEN-LAST:event_btnAddUserActionPerformed

    private void btnResetPwActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetPwActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn đặt lại mật khẩu cho người dùng đã chọn?",
                "Xác nhận đặt lại mật khẩu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            NguoiDungHeThongDAO.update(new NguoiDungHeThong(txtUsername.getText(), hashedDefault));
            JOptionPane.showMessageDialog(null, "Đã đặt lại mật khẩu. Mật khẩu mới là '12345678'", "Đặt lại mật khẩu",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        btnResetInputActionPerformed(null);

    }// GEN-LAST:event_btnResetPwActionPerformed

    private void btnDeleteUsersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteUsersActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa người dùng đã chọn?", "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            NguoiDungHeThongDAO.delete(txtUsername.getText());
            JOptionPane.showMessageDialog(null, "Đã xóa người dùng", "Xóa người dùng", JOptionPane.INFORMATION_MESSAGE);
        }
        loadData(null);
        btnResetInputActionPerformed(null);
    }// GEN-LAST:event_btnDeleteUsersActionPerformed

    private void btnResetInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetInputActionPerformed
        txtFullName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtRePassword.setText("");
        enableTextbox(true);
        btnAddUser.setEnabled(true);
        btnDeleteUsers.setEnabled(false);
        btnResetPw.setEnabled(false);
        jTable1.clearSelection();
    }// GEN-LAST:event_btnResetInputActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimKiemActionPerformed
        if (txtTimKiem.getText().isEmpty()) {
            loadData(null);
        } else {
            loadData(txtTimKiem.getText());
        }
    }// GEN-LAST:event_btnTimKiemActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedRow() == -1) {
            return;
        }

        int index = jTable1.getSelectedRow();

        enableTextbox(false);

        txtFullName.setText(users.get(index).getFull_name());
        txtUsername.setText(users.get(index).getUsername());
        btnResetPw.setEnabled(true);
        btnDeleteUsers.setEnabled(true);
        btnAddUser.setEnabled(false);
    }// GEN-LAST:event_jTable1MouseClicked

    private void enableTextbox(boolean b) {
        txtFullName.setEnabled(b);
        txtUsername.setEnabled(b);
        txtPassword.setEnabled(b);
        txtRePassword.setEnabled(b);
    }

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    // default look and feel.
    // * For details see
    // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(DialogNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(DialogNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(DialogNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(DialogNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>

    // /* Create and display the dialog */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // DialogNguoiDung dialog = new DialogNguoiDung(new javax.swing.JFrame(), true);
    // dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    // @Override
    // public void windowClosing(java.awt.event.WindowEvent e) {
    // System.exit(0);
    // }
    // });
    // dialog.setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDeleteUsers;
    private javax.swing.JButton btnResetInput;
    private javax.swing.JButton btnResetPw;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
