/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aptech.project2.nhom2.gui.dialoguebox;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.stream.Collectors;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import org.apache.commons.io.FileUtils;

import aptech.project2.nhom2.dao.SinhVienDAO;
import aptech.project2.nhom2.model.ComboBoxData;
import aptech.project2.nhom2.model.SinhVien;
import aptech.project2.nhom2.util.StringWorker;

/**
 *
 * @author Admin
 */
public class DialogSinhVien extends javax.swing.JDialog {
    private SinhVienDAO sinhVienDAO = new SinhVienDAO();// gán biến đại diện cho sinhviendao

    private List<SinhVien> sv;// tạo list

    /**
     * Creates new form DialogSinhVien
     */

    private String fileExt;

    public DialogSinhVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        showSinhvien(null);

        this.setLocationRelativeTo(null);

        this.pack();
    }

    private void showSinhvien(String timKiem) {
        DefaultTableModel person = (DefaultTableModel) jTable1.getModel();
        sv = sinhVienDAO.findAll(); // pull dữ liệu từ database
        person.setRowCount(0);// reset
        if (timKiem == null) {
            sv.forEach(ps -> {
                person.addRow(new Object[] { ps.getId(), ps.getTen(), ps.getGioiTinh().getLabel(), ps.getEmail(),
                        ps.getSdt() });
            });
        } else {
            List<SinhVien> locTimKiem = sv.stream().filter(ps -> ps.getTen().contains(txtTimKiem.getText()))
                    .collect(Collectors.toList());
            locTimKiem.forEach(ps -> {
                person.addRow(new Object[] { ps.getId(), ps.getTen(), ps.getGioiTinh().getLabel(), ps.getEmail(),
                        ps.getSdt() });
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTenSinhvien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbGioiTinh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnAddSinhVien = new javax.swing.JButton();
        btnEditSinhVien = new javax.swing.JButton();
        btnDeleteSinhVien = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFileAnh = new javax.swing.JTextField();
        btnChonAnh = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtMaSinhVien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        bntTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh sách sinh viên");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] { "Mã sinh viên", "Tên sinh viên", "Giới tính", "Email", "Số điện thoại" }) {
            boolean[] canEdit = new boolean[] { false, false, false, false, false };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sách"));

        jLabel7.setText("Tên sinh viên");

        jLabel8.setText("Giới tính");

        cmbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cmbGioiTinh.setSelectedIndex(-1);

        jLabel9.setText("Mã sinh viên");

        btnAddSinhVien.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_add_16px.png"))); // NOI18N
        btnAddSinhVien.setText("Thêm sinh viên");
        btnAddSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnAddSinhVienActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        btnEditSinhVien.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_edit_16px.png"))); // NOI18N
        btnEditSinhVien.setText("Sửa thông tin");
        btnEditSinhVien.setEnabled(false);
        btnEditSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnEditSinhVienActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        btnDeleteSinhVien.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_delete_16px.png"))); // NOI18N
        btnDeleteSinhVien.setText("Xóa sách");
        btnDeleteSinhVien.setEnabled(false);
        btnDeleteSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSinhVienActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_reset_16px.png"))); // NOI18N
        btnReset.setText("Điền lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel12.setText("Email");

        jLabel13.setText("Số điện thoại");

        jLabel14.setText("Ảnh");

        txtFileAnh.setEnabled(false);

        btnChonAnh.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_browse_folder_16px.png"))); // NOI18N
        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        btnChiTiet.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_info_16px.png"))); // NOI18N
        btnChiTiet.setText("Xem chi tiết");
        btnChiTiet.setEnabled(false);
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel14)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12).addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(txtFileAnh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnChonAnh))
                                .addComponent(txtEmail)
                                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(btnAddSinhVien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEditSinhVien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeleteSinhVien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnReset).addGap(133, 133, 133).addComponent(btnChiTiet)
                                        .addGap(0, 50, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTenSinhvien, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13).addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtMaSinhVien).addComponent(txtSoDienThoai))))
                        .addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTenSinhvien, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12).addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(txtFileAnh, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnChonAnh))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDeleteSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jLabel1.setText("Tìm kiếm theo tên");

        bntTimKiem.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/aptech/project2/nhom2/gui/icons/buttonicons/icons8_search_16px.png"))); // NOI18N
        bntTimKiem.setText("Tìm kiếm");
        bntTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup().addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup().addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTimKiem)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bntTimKiem)))
                                .addContainerGap())
                .addComponent(jScrollPane1));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bntTimKiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MousePressed
        if (jTable1.getSelectedRow() != -1) {
            int index = jTable1.getSelectedRow();

            buttonStatus(true);

            cmbGioiTinh.setSelectedIndex(sv.get(index).getGioiTinh().getValue());

            txtMaSinhVien.setText(sv.get(index).getId());
            txtTenSinhvien.setText(sv.get(index).getTen());
            txtEmail.setText(sv.get(index).getEmail());
            txtSoDienThoai.setText(sv.get(index).getSdt());

            txtMaSinhVien.setEditable(false);
        }

    }// GEN-LAST:event_jTable1MousePressed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChiTietActionPerformed
        SinhVien anh;
        anh = sv.stream().filter(ps -> ps.getId().equals(txtMaSinhVien.getText())).findAny().orElse(null);
        DialogChiTietSinhVien chiTietSinhVien = new DialogChiTietSinhVien(null, true, anh);
        chiTietSinhVien.setVisible(true);
    }// GEN-LAST:event_btnChiTietActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChonAnhActionPerformed
        JFileChooser chooser = new JFileChooser();

        chooser.setDialogTitle("Chọn file ảnh");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("Image files", "jpg", "png"));
        int sts = chooser.showOpenDialog(null);

        if (sts == JFileChooser.APPROVE_OPTION) {
            File selected = chooser.getSelectedFile();
            if (FileUtils.getExtension(selected.getAbsolutePath()).equals("jpg")
                    || FileUtils.getExtension(selected.getAbsolutePath()).equals("png")) {
                txtFileAnh.setText(selected.getAbsolutePath());
                fileExt = FileUtils.getExtension(selected.getAbsolutePath());
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng chỉ chọn file ảnh có định dạng jpg hoặc png",
                        "Sai định dạng ảnh", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    }// GEN-LAST:event_btnChonAnhActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
        txtMaSinhVien.setText("");
        txtEmail.setText("");
        txtFileAnh.setText("");
        txtTenSinhvien.setText("");
        txtSoDienThoai.setText("");
        cmbGioiTinh.setSelectedIndex(-1);
        txtMaSinhVien.setEditable(true);
        jTable1.clearSelection();
        buttonStatus(false);

    }// GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteSinhVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteSinhVienActionPerformed
        int index = jTable1.getSelectedRow();
        String id = sv.get(index).getId();

        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa sinh viên đã chọn?", "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == 0) {
            sinhVienDAO.delete(id);
        }
        showSinhvien(null);
        btnResetActionPerformed(null);
        buttonStatus(false);
    }// GEN-LAST:event_btnDeleteSinhVienActionPerformed

    private void btnEditSinhVienActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_btnEditSinhVienActionPerformed

        if (txtTenSinhvien.getText().isEmpty() || txtEmail.getText().isEmpty() || txtSoDienThoai.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Vui lòng nhập các thông tin để thực hiện thao tác sửa thông tin sinh viên", "Chưa nhập dữ liệu",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        SinhVien test = sv.stream()
                .filter(ps -> ps.getEmail().equals(txtEmail.getText()) && !ps.getId().equals(txtMaSinhVien.getText())
                        && ps.getSdt().equals(txtSoDienThoai.getText())
                        && ps.getGioiTinh().getValue() == cmbGioiTinh.getSelectedIndex())
                .findAny().orElse(null);
        if (test != null) {
            JOptionPane.showMessageDialog(null,
                    "Thông tin chỉnh sửa trùng với thông tin sinh viên hiện đang có trong hệ thống", "Trùng thông tin",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!txtFileAnh.getText().isEmpty()) {
            String file = StringWorker.removeAccentedCharacter(txtMaSinhVien.getText())
                    + System.currentTimeMillis() / 100 + "." + fileExt;
            FileUtils.copyFile(new File(txtFileAnh.getText()), new File("image/student/" + file));
            sinhVienDAO.update(new SinhVien(txtMaSinhVien.getText(), txtTenSinhvien.getText(), txtSoDienThoai.getText(),
                    new ComboBoxData(cmbGioiTinh.getSelectedIndex(), null), txtEmail.getText(), file));

        }
        sinhVienDAO.update(new SinhVien(txtMaSinhVien.getText(), txtTenSinhvien.getText(), txtSoDienThoai.getText(),
                new ComboBoxData(cmbGioiTinh.getSelectedIndex(), null), txtEmail.getText(), null));

        JOptionPane.showMessageDialog(null, " Đã thêm Sinh viên thành công vào trong hệ thống!", "Thêm sinh viên",
                JOptionPane.INFORMATION_MESSAGE);

        showSinhvien(null);
        btnResetActionPerformed(null);
        buttonStatus(false);

    }// GEN-LAST:event_btnEditSinhVienActionPerformed

    private void btnAddSinhVienActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_btnAddSinhVienActionPerformed
        // lọc input
        if (txtMaSinhVien.getText().isEmpty() || txtTenSinhvien.getText().isEmpty() || txtEmail.getText().isEmpty()
                || txtSoDienThoai.getText().isEmpty() || txtFileAnh.getText().isEmpty()
                || cmbGioiTinh.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập các thông tin để thực hiện thao tác thêm sinh viên",
                    "Chưa nhập dữ liệu", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // so sánh input với list sinh vien
        SinhVien test = sv
                .stream().filter(ps -> ps.getId().equals(txtMaSinhVien.getText())
                        && ps.getEmail().equals(txtEmail.getText()) && ps.getSdt().equals(txtSoDienThoai.getText()))
                .findAny().orElse(null);

        if (test != null) {
            JOptionPane.showMessageDialog(null, "Sinh viên cần thêm đã tồn tại trong hệ thống!", "Thêm sinh viên",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // copy file chỉ định thành dạng có tên và dịnh dạng nằm ở đường dẫn chỉ định
        // add vào database
        String file = StringWorker.removeAccentedCharacter(txtMaSinhVien.getText()) + System.currentTimeMillis() / 100
                + "." + fileExt;
        FileUtils.copyFile(new File(txtFileAnh.getText()), new File("image/student/" + file));
        sinhVienDAO.addNew(new SinhVien(txtMaSinhVien.getText(), txtTenSinhvien.getText(), txtSoDienThoai.getText(),
                new ComboBoxData(cmbGioiTinh.getSelectedIndex(), null), txtEmail.getText(), file));

        JOptionPane.showMessageDialog(null, " Đã thêm Sinh viên thành công vào trong hệ thống!", "Thêm sinh viên",
                JOptionPane.INFORMATION_MESSAGE);

        showSinhvien(null);

    }// GEN-LAST:event_btnAddSinhVienActionPerformed

    private void bntTimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntTimKiemActionPerformed
        if (txtTimKiem.getText().isEmpty()) {
            showSinhvien(null);
        } else {
            showSinhvien(txtTimKiem.getText());
        }
    }// GEN-LAST:event_bntTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // // (optional) ">
    // /*
    // * If Nimbus (introduced in Java SE 6) is not available, stay with the default
    // * look and feel. For details see
    // * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(DialogSinhVien.class.getName()).log(java.util.logging.Level.SEVERE,
    // null,
    // ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(DialogSinhVien.class.getName()).log(java.util.logging.Level.SEVERE,
    // null,
    // ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(DialogSinhVien.class.getName()).log(java.util.logging.Level.SEVERE,
    // null,
    // ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(DialogSinhVien.class.getName()).log(java.util.logging.Level.SEVERE,
    // null,
    // ex);
    // }
    // // </editor-fold>

    // /* Create and display the dialog */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // DialogSinhVien dialog = new DialogSinhVien(new javax.swing.JFrame(), true);
    // dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    // @Override
    // public void windowClosing(java.awt.event.WindowEvent e) {
    // System.exit(0);
    // }
    // });
    // dialog.setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntTimKiem;
    private javax.swing.JButton btnAddSinhVien;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnDeleteSinhVien;
    private javax.swing.JButton btnEditSinhVien;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFileAnh;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenSinhvien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void buttonStatus(boolean status) {
        btnEditSinhVien.setEnabled(status);
        btnDeleteSinhVien.setEnabled(status);
        btnChiTiet.setEnabled(status);
    }
}
