/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aptech.project2.nhom2.gui.dialoguebox;

import java.util.List;

import javax.swing.JOptionPane;

import aptech.project2.nhom2.dao.MuonTraSachDAO;
import aptech.project2.nhom2.dao.SinhVienDAO;
import aptech.project2.nhom2.dao.ThongTinSachDAO;
import aptech.project2.nhom2.model.MuonSach;
import aptech.project2.nhom2.model.SinhVien;
import aptech.project2.nhom2.model.ThongTinSach;

/**
 *
 * @author Mirai
 */
public class DialogMuonSach extends javax.swing.JDialog {

	private ThongTinSachDAO sachDao = new ThongTinSachDAO();
	private SinhVienDAO svDao = new SinhVienDAO();

	private ThongTinSach dataSach;
	private SinhVien dataSV;

	private List<ThongTinSach> sach = sachDao.findAll();
	private List<SinhVien> sinhVien = svDao.findAll();

	private DialogChiTietSach dlg;

	/**
	 * Creates new form DialogMuonSach
	 */
	public DialogMuonSach(java.awt.Frame parent, boolean modal, ThongTinSach sach, SinhVien sv) {
		super(parent, modal);
		initComponents();
		
		hideFlag(false);

		initInput(sach, sv);

		this.setLocationRelativeTo(null);
		this.pack();
	}

	private void hideFlag(boolean b) {
		lbTenSach.setVisible(b);
		lbTenSinhVien.setVisible(b);
		lbBookStatus.setVisible(b);
	}

	private void initInput(ThongTinSach sach, SinhVien sv) {
		if (sach != null) {
			numMaSach.setValue(sach.getId());
			lbTenSach.setVisible(true);
			lbTenSach.setText("Tên sách: " + sach.getTen());
			lbBookStatus.setVisible(true);
			lbBookStatus.setText("Tình trạng: Sách còn trong thư viện");
			dataSach = sach;
		}
		if (sv != null) {
			txtMaSinhVien.setText(sv.getId());
			lbTenSinhVien.setText("Tên sinh viên: " + sv.getTen());
			dataSV = sv;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        btnChonSinhVien = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnChonSach = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnMuonSach = new javax.swing.JButton();
        btnDienLai = new javax.swing.JButton();
        lbTenSinhVien = new javax.swing.JLabel();
        lbTenSach = new javax.swing.JLabel();
        numMaSach = new javax.swing.JSpinner();
        lbBookStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mượn sách");

        jLabel1.setText("Mã sinh viên");

        txtMaSinhVien.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        btnChonSinhVien.setText("Tìm sinh viên");
        btnChonSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonSinhVienActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã sách");

        btnChonSach.setText("Kiểm tra tình trạng");
        btnChonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonSachActionPerformed(evt);
            }
        });

        jLabel3.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        btnMuonSach.setText("Mượn sách");
        btnMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonSachActionPerformed(evt);
            }
        });

        btnDienLai.setText("Điền lại");
        btnDienLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDienLaiActionPerformed(evt);
            }
        });

        lbTenSinhVien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTenSinhVien.setText("Tên sinh viên: ");

        lbTenSach.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTenSach.setForeground(new java.awt.Color(51, 51, 255));
        lbTenSach.setText("Tên sách: ");
        lbTenSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbTenSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTenSachMouseClicked(evt);
            }
        });

        numMaSach.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lbBookStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbBookStatus.setText("Tình trạng: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMuonSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDienLai))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numMaSach)
                                        .addGap(137, 137, 137)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnChonSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnChonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTenSinhVien)
                                    .addComponent(lbTenSach)
                                    .addComponent(lbBookStatus))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonSinhVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTenSinhVien)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnChonSach)
                    .addComponent(numMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lbTenSach)
                .addGap(11, 11, 11)
                .addComponent(lbBookStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMuonSach)
                    .addComponent(btnDienLai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnChonSinhVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChonSinhVienActionPerformed
		SinhVien searchSinhVien = sinhVien.stream().filter(it -> it.getId().equals(txtMaSinhVien.getText())).findAny()
				.orElse(null);
		if (searchSinhVien != null) {
			lbTenSinhVien.setVisible(true);
			lbTenSinhVien.setText("Tên sinh viên: " + searchSinhVien.getTen());
			dataSV = searchSinhVien;
			btnMuonSach.setVisible(true);
		} else {
			lbTenSinhVien.setVisible(false);
			JOptionPane.showMessageDialog(null, "Không tìm thấy sinh viên với mã sinh viên đã nhập", "Không tìm thấy",
					JOptionPane.INFORMATION_MESSAGE);
			btnMuonSach.setEnabled(false);
		}
		this.pack();
	}// GEN-LAST:event_btnChonSinhVienActionPerformed

	private void btnChonSachActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChonSachActionPerformed
		ThongTinSach search = sach.stream().filter(it -> it.getId() == (int) numMaSach.getValue()).findAny()
				.orElse(null);
		if (search != null) {
			lbTenSach.setVisible(true);
			lbTenSach.setText("Tên sách: " + search.getTen());
			dataSach = search;
			if (search.getSoLuong() == search.getSoLuongDaMuon()) {
				btnMuonSach.setEnabled(false);
				lbBookStatus.setVisible(true);
				lbBookStatus.setText("Tình trạng: Sách đã mượn hết");
				btnMuonSach.setEnabled(false);
			} else {
				btnMuonSach.setEnabled(true);
				lbBookStatus.setVisible(true);
				lbBookStatus.setText("Tình trạng: Sách còn trong thư viện");
				btnMuonSach.setEnabled(true);
			}
		} else {
			JOptionPane.showMessageDialog(null, "Không tìm thấy sách có mã đã nhập", "Không tìm thấy",
					JOptionPane.INFORMATION_MESSAGE);
			lbTenSach.setVisible(false);
			lbBookStatus.setVisible(false);
		}
		this.pack();
	}// GEN-LAST:event_btnChonSachActionPerformed

	private void btnMuonSachActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMuonSachActionPerformed
		if (txtMaSinhVien.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ các thông tin trước khi tiến hành mượn sách",
					"Thiếu dữ liệu", JOptionPane.INFORMATION_MESSAGE);
			return;
		}

		if (lbTenSach.isVisible() == false || lbTenSinhVien.isVisible()) {
			JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra tình trạng sách và kiểm tra thông tin sinh viên trước khi tiến hành mượn sách",
			"Chưa kiểm tra thông tin", JOptionPane.INFORMATION_MESSAGE);
			return;
		}

		if (txtGhiChu.getText().isEmpty()) {
			MuonTraSachDAO.borrowBooks(new MuonSach(dataSV, dataSach, "Không có", 0));

		} else {
			MuonTraSachDAO.borrowBooks(new MuonSach(dataSV, dataSach, txtGhiChu.getText(), 0));
		}

		JOptionPane.showMessageDialog(null, "Đã mượn sách thành công", "Mượn sách", JOptionPane.INFORMATION_MESSAGE);
		this.dispose();
	}// GEN-LAST:event_btnMuonSachActionPerformed

	private void btnDienLaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDienLaiActionPerformed
		hideFlag(false);
		txtGhiChu.setText("");
		txtMaSinhVien.setText("");
		numMaSach.setValue(1);
		this.pack();
	}// GEN-LAST:event_btnDienLaiActionPerformed

	private void lbTenSachMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbTenSachMouseClicked
		dlg = new DialogChiTietSach(null, true, dataSach);
		dlg.setVisible(true);
	}// GEN-LAST:event_lbTenSachMouseClicked

	/**
	 * @param args the command line arguments
	 */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// // (optional) ">
	// /*
	// * If Nimbus (introduced in Java SE 6) is not available, stay with the default
	// * look and feel. For details see
	// * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info :
	// javax.swing.UIManager.getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(DialogMuonSach.class.getName()).log(java.util.logging.Level.SEVERE,
	// null,
	// ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(DialogMuonSach.class.getName()).log(java.util.logging.Level.SEVERE,
	// null,
	// ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(DialogMuonSach.class.getName()).log(java.util.logging.Level.SEVERE,
	// null,
	// ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(DialogMuonSach.class.getName()).log(java.util.logging.Level.SEVERE,
	// null,
	// ex);
	// }
	// // </editor-fold>

	// /* Create and display the dialog */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// DialogMuonSach dialog = new DialogMuonSach(new javax.swing.JFrame(), true);
	// dialog.addWindowListener(new java.awt.event.WindowAdapter() {
	// @Override
	// public void windowClosing(java.awt.event.WindowEvent e) {
	// System.exit(0);
	// }
	// });
	// dialog.setVisible(true);
	// }
	// });
	// }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonSach;
    private javax.swing.JButton btnChonSinhVien;
    private javax.swing.JButton btnDienLai;
    private javax.swing.JButton btnMuonSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBookStatus;
    private javax.swing.JLabel lbTenSach;
    private javax.swing.JLabel lbTenSinhVien;
    private javax.swing.JSpinner numMaSach;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaSinhVien;
    // End of variables declaration//GEN-END:variables
}
